# Python Test 100
## Group 4 Questions 1..6

### -------------------- Question 1 --------------------

timeseries - a series indexed by datetime objects (or similar objects)<br>
Give examples of creating a timeseries

#### Answer

In [4]:
import sys, os
import pandas as pd
import numpy as np
import datetime as dt
mydates = [dt.datetime(2011,1,2), 
           dt.datetime(2011,1,5), 
           dt.datetime(2011,1,7), 
           dt.datetime(2011,1,8), 
           dt.datetime(2011,1,10), 
           dt.datetime(2011,1,12)]

ts = pd.Series(np.random.randn(6), index=mydates) 
print(ts)

ts = pd.Series(np.random.randn(1000), 
               index = pd.date_range('1/1/2000',periods=1000, normalize=True))
print("-"*40)
print(ts)

#   note: in above we use normalize=True to zero-out times. 
#   so ts.index = [2000-01-01 00:00:00, ..., 2002-09-26 00:00:00]

2011-01-02    1.248379
2011-01-05    0.515979
2011-01-07    1.180099
2011-01-08    0.051372
2011-01-10    0.131577
2011-01-12    0.651978
dtype: float64
----------------------------------------
2000-01-01    0.164044
2000-01-02   -0.389707
2000-01-03    1.334444
2000-01-04   -0.465228
2000-01-05   -0.633773
2000-01-06   -0.022118
2000-01-07   -1.618976
2000-01-08   -0.397228
2000-01-09    0.314000
2000-01-10    0.035972
2000-01-11   -0.534589
2000-01-12   -0.096238
2000-01-13   -1.305551
2000-01-14    1.340112
2000-01-15   -0.849002
2000-01-16    0.398102
2000-01-17    0.714274
2000-01-18    0.234081
2000-01-19    0.989357
2000-01-20    0.298375
2000-01-21   -1.281326
2000-01-22    0.040632
2000-01-23    1.766373
2000-01-24    0.977334
2000-01-25   -1.917145
2000-01-26   -0.631120
2000-01-27   -0.493033
2000-01-28   -1.035096
2000-01-29   -0.540603
2000-01-30   -0.083033
                ...
2002-08-28    1.354886
2002-08-29    0.945806
2002-08-30   -1.056407
2002-08-31   -0.798627
2002-09-01   -2.246368
2002-09-02   -0.416663
2002-09-03    0.379477
2002-09-04   -1.649236
2002-09-05   -0.994477
2002-09-06   -0.468928
2002-09-07    0.402136
2002-09-08    1.129017
2002-09-09    1.376367
2002-09-10   -1.169489
2002-09-11    0.744669
2002-09-12   -0.180815
2002-09-13   -2.112176
2002-09-14   -2.046058
2002-09-15    1.488992
2002-09-16    1.716020
2002-09-17    1.300052
2002-09-18   -0.019925
2002-09-19    1.368032
2002-09-20   -0.357371
2002-09-21    0.551503
2002-09-22   -0.194849
2002-09-23    0.493029
2002-09-24    0.494812
2002-09-25   -0.389471
2002-09-26   -0.460564
Freq: D, Length: 1000, dtype: float64

### -------------------- Question 2 --------------------

Show how to sort dictionary keys by keys or by values

#### Answer

In [5]:
dd = {11:5, 22:4, 33:3, 44:2, 55:1}
print(sorted(dd))                          # [11, 22, 33, 44, 55]
print(sorted(dd,key=dd.get))               # [55, 44, 33, 22, 11]
print(sorted(dd,key=dd.get, reverse=True)) # [11, 22, 33, 44, 55]

[11, 22, 33, 44, 55]
[55, 44, 33, 22, 11]
[11, 22, 33, 44, 55]

### -------------------- Question 3 --------------------

Show the uses sorted() function by using each of the parameters<br>
<b>sorted(iterable, cmp=None, key=None, reverse=False)</b>

#### Answer

In [6]:
# sorted(iterable, cmp=None, key=None, reverse=False) - returns new sorted list

aa=[1,2,3,11,12,13]
print(sorted(aa))                       # [1, 2, 3, 11, 12, 13]
print(sorted(aa,key=str))               # [1, 11, 12, 13, 2, 3]
print(sorted(aa,key=int))               # [1, 2, 3, 11, 12, 13]
print(sorted(aa,key=int,reverse=True))  # [13, 12, 11, 3, 2, 1]
print(sorted(aa,key=str,reverse=True))  # [3, 2, 13, 12, 11, 1]

[1, 2, 3, 11, 12, 13]
[1, 11, 12, 13, 2, 3]
[1, 2, 3, 11, 12, 13]
[13, 12, 11, 3, 2, 1]
[3, 2, 13, 12, 11, 1]

### -------------------- Question 4 --------------------

Show the variables that I have defined in current ipython session
<br>    (dir(), locals(), globals() return too much)

#### Answer

In [7]:
# use magic command %who to print the list
# use magic command %who_ls to return the list

mylist = %who_ls
print(mylist)

['aa', 'dd', 'dt', 'mydates', 'ts']

### -------------------- Question 5 --------------------

Calculate number of business days between two dates

#### Answer

In [8]:
import numpy as np
import datetime as dt

dt1 = dt.date(2019,4,23)
dt2 = dt.date(2019,4,25)

# use numpy
cnt_np = np.busday_count(dt1, dt2)
print("np:",cnt_np)

# efficient way to calculate 
def working_days_in_range(from_date, to_date):
    from_weekday = from_date.weekday()
    to_weekday = to_date.weekday()
    # If start date is after Friday, modify it to Monday
    if from_weekday > 4:
        from_weekday = 0
    day_diff = to_weekday - from_weekday
    whole_weeks = ((to_date - from_date).days - day_diff) / 7
    workdays_in_whole_weeks = whole_weeks * 5
    beginning_end_correction = min(day_diff, 5) - (max(to_weekday - 4, 0) % 5)
    working_days = workdays_in_whole_weeks + beginning_end_correction
    # Final sanity check (i.e. if the entire range is weekends)
    return int(max(0, working_days))

cnt_eff = working_days_in_range(dt1, dt2)
print("eff:",cnt_eff)

# special libraries for bus. days calculations
# https://pypi.org/project/workdays/
# https://bitbucket.org/shelldweller/python-bizdatetime
pass

np: 2
eff: 2

In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame({ 'A' : ['1/1/2013', '2/2/2013', '3/3/2013'],
                    'B': ['1/12/2013', '4/4/2013', '3/3/2013']})
display(df)
print("-"*40)

df['Ad'] = pd.to_datetime(df['A'])
df['Bd'] = pd.to_datetime(df['B'])

display(df)
print("-"*40)

A = np.array(df['Ad'].values.astype('datetime64[D]'))
B = np.array(df['Bd'].values.astype('datetime64[D]'))
print(A)
print("-"*40)

df['DIFF'] = np.busday_count(A,B)
display(df)

          A          B
0  1/1/2013  1/12/2013
1  2/2/2013   4/4/2013
2  3/3/2013   3/3/2013

----------------------------------------

          A          B         Ad         Bd
0  1/1/2013  1/12/2013 2013-01-01 2013-01-12
1  2/2/2013   4/4/2013 2013-02-02 2013-04-04
2  3/3/2013   3/3/2013 2013-03-03 2013-03-03

----------------------------------------
['2013-01-01' '2013-02-02' '2013-03-03']
----------------------------------------

          A          B         Ad         Bd  DIFF
0  1/1/2013  1/12/2013 2013-01-01 2013-01-12     9
1  2/2/2013   4/4/2013 2013-02-02 2013-04-04    43
2  3/3/2013   3/3/2013 2013-03-03 2013-03-03     0

### -------------------- Question 6 --------------------

How to write/read binary strings

In [10]:
import os,sys

fname = "/tmp/junk_binary.txt"

# --------------------------
# Writing binary file
# --------------------------
fh = open(fname,"wb")
for row in range(3):
    ss=b""
    for ii in range(5): 
        ss+=ii.to_bytes(1,"big")
    ss += b"\n"
    fh.write(ss)
fh.close()

# --------------------------
# Reading binary file
# --------------------------

with open(fname,'rb') as fh:
    byte_txt = fh.read()

print("type = ", type(byte_txt), ", len = ",len(byte_txt))

arr = byte_txt.split(b'\n')
print("length = ", len(arr))
print(arr)

type =  <class 'bytes'> , len =  18
length =  4
[b'\x00\x01\x02\x03\x04', b'\x00\x01\x02\x03\x04', b'\x00\x01\x02\x03\x04', b'']